colors: true

commit-msg:
  jobs:
    - name: commitlint
      run: pnpm commitlint --edit {1}

pre-commit:
  parallel: false

  jobs:
    - name: format
      glob: '*.{ts,tsx,js,json,css}'
      run: pnpm format && git add {staged_files}

    - name: lint
      glob: '*.{ts,tsx,js,json,css}'
      run: pnpm lint

    - name: typecheck
      glob: '*.{ts,tsx,json}'
      run: pnpm typecheck

pre-push:
  parallel: true

  jobs:
    - name: dead-code
      glob: '*.{ts,tsx,js,jsx,mts,cts,mjs,cjs,json,css,yml,yaml}'
      run: pnpm audit:dead-code

    - name: test
      glob: '*.{ts,tsx,json}'
      run: pnpm test

#    - name: packages-audit
#      run: pnpm audit
