allowBuilds:
  '@biomejs/biome': true
  '@parcel/watcher': false
  '@swc/core': true
  esbuild: true
  lefthook: true
  sharp: true
engineStrict: true
saveExact: true
minimumReleaseAge: 1440
patchedDependencies:
  next-themes@0.4.6: patches/next-themes@0.4.6.patch
